bookstore_app/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources :books
  resources :authors
  resources :genres
  resources :publishers
  resources :novels



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookstore_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookstore_app/app/models/author.rb
class Author < ApplicationRecord
    has_many :novels
    validates :fname, presence: true
    validates :lname, presence: true
    validates :bio, presence: true
end

bookstore_app/app/models/book.rb
class Book < ApplicationRecord
end

bookstore_app/app/models/genre.rb
class Genre < ApplicationRecord
    has_many :novels
end

bookstore_app/app/models/novel.rb
class Novel < ApplicationRecord
    belongs_to :author
    belongs_to :genre
    belongs_to :publisher
end

bookstore_app/app/models/publisher.rb
class Publisher < ApplicationRecord
    has_many :novels
end

bookstore_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

bookstore_app/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
        @authors=Author.all 
    end
    def new 
    end
   # private
   def show 
    @author=Author.find(params[:id])
  end
    def author_params
        params.require(:author).permit(:fname, :lname, :bio)
    end
    def create 
        @author = Author.new(author_params)
        if @author.save
            redirect_to @author
        else
            render 'new'
        end
    end
end

bookstore_app/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books=Book.all
  end
  
  def new
  end
  
#  private
   def create
    # render plain: params[:book].inspect
    @book=Book.new(book_params)
    @book.save
    redirect_to @book
  end 
  def show 
    @book=Book.find(params[:id])
  end
#end
  def book_params
    params.require(:book).permit(:title, :price, :book_id, :publisher,
      :description, :number)
    end
end

bookstore_app/app/controllers/genres_controller.rb
class GenresController < ApplicationController
    def index
        @genres=Genre.all 
    end

    def new 
    end
    def create 
        @genre = Genre.new(genre_params)
        if @genre.save
            redirect_to @genre
        else
            render 'new'
        end
    end
   # private
   def show 
    @genre=Genre.find(params[:id])
    end
    
    def genre_params
        params.require(:genre).permit(:name)
    end
    
end

bookstore_app/app/controllers/novels_controller.rb
class NovelsController < ApplicationController
        def index
            @novels=Novel.all 
        end
    
        def new 
        end
        def create 
            @novel = Novel.new(novel_params)
            if @novel.save
                redirect_to @novel
            else
                render 'new'
            end
        end
        def show 
            @novel = Novel.find(params[:id])
        end

        def edit 
            @novel = Novel.find(params[:id])
            
        end

        def update 
#             @novel = Novel.find(params[:id])
#             puts @novel;
#  if @novel.update(novel_params)
#  redirect_to @novel
#  else
#  render 'edit'
#  end
 @novel = Novel.find(params[:id])
  @novel.update(name: params[:novel][:name],genre_id: params[:novel][:genre_id],author_id: params[:novel][:author_id],publisher_id: params[:novel][:publisher_id],isbn: params[:novel][:isbn],price: params[:novel][:price],publication: params[:novel][:publication],format: params[:novel][:format],description: params[:novel][:description],pages: params[:novel][:pages])
  redirect_to novels_path(@novel)

        end
        
       # private
       
        
        def novel_params
            params.permit( :name, :country , :genre_id , :author_id , :publisher_id , :isbn , :price , :publication , :format , :description , :pages  )
        end

         def destroy
            @novel = Novel.find(params[:id])
            @novel.destroy
            redirect_to novels_path
        end
        
    
end

bookstore_app/app/controllers/publisher_controller.rb
class PublisherController < ApplicationController
    def index
        @publishers=Publisher.all 
    end

    def new 
    end
    def create 
        @publisher = Publisher.new(publisher_params)
        if @publisher.save
            redirect_to @publisher
        else
            render 'new'
        end
    end
    def show 
        @publisher = Publisher.find(params[:id])
    end
    
   # private
   
    
    def publisher_params
        params.require(:publisher).permit( :name, :country)
    end
    
end

bookstore_app/app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
    def index
        @publishers=Publisher.all 
    end

    def new 
    end
    def create 
        @publisher = Publisher.new(publisher_params)
        if @publisher.save
            redirect_to @publisher
        else
            render 'new'
        end
    end
    def show 
        @publisher = Publisher.find(params[:id])
    end
    
   # private
   
    
    def publisher_params
        params.require(:publisher).permit( :name, :country)
    end
end

bookstore_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

bookstore_app/app/helpers/application_helper.rb
module ApplicationHelper
end

bookstore_app/app/helpers/authors_helper.rb
module AuthorsHelper
end

bookstore_app/app/helpers/books_helper.rb
module BooksHelper
end

bookstore_app/app/helpers/genres_helper.rb
module GenresHelper
end

bookstore_app/app/helpers/novels_helper.rb
module NovelsHelper
end

bookstore_app/app/helpers/publisher_helper.rb
module PublisherHelper
end

bookstore_app/app/helpers/publishers_helper.rb
module PublishersHelper
end

bookstore_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bookstore_app/app/views/authors/index.html.erb
<div class="container">
<h2> Books Available </h2>
<table border="1" class="table">
<tr>
<th> fname</th>
<th> lname</th>
<th> bio</th>
</tr>
<% @authors.each do |author| %>
<tr>
<td> <%= author.fname %> </td>
<td> <%= author.lname %> </td>
<td> <%= author.bio %> </td>


</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/authors/new.html.erb
<div class="container">
<h2>Add New Author</h2>
<%= form_for :author, url: authors_path do |f| %>
<div class="form-group">
<%= f.label :fname %><br />
<%= f.text_field :fname, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :lname %><br />
<%= f.text_field :lname, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :bio %><br />
<%= f.text_field :bio, class:'form-control' %><br />
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", authors_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/authors/show.html.erb
<div class="container">
<h3>Author Details</h3>
<p>fname: <%= @author.fname %> </p>
<p>lname: <%= @author.lname %> </p>
<p>bio: <%= @author.bio %> </p>
</div>

bookstore_app/app/views/books/index.html.erb
<div class="container">
<h2> Books Available </h2>
<table border="1" class="table">
<tr>
<th> Book Title</th>
<th> Book Code</th>
<th> Book Price</th>
<th> Publisher</th>
<th> Book Description</th>
<th> Number Of Copies</th>
<th> Book Page</th></tr>
<% @books.each do |book| %>
<tr>
<td> <%= book.title %> </td>
<td> <%= book.number %> </td>
<td> <%= book.price%> </td>
<td> <%= book.publisher%> </td>
<td> <%= book.description%> </td>
<td> <%= book.number%> </td>
<td> <%= link_to 'Book Page', book_path(book) %> </td>
</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/books/new.html.erb
<div class="container">
<h1> Add New Book</h1>
<%= form_for :book, url: books_path do |f| %><div class="form-group">
<%= f.label :title %>
<%= f.text_field :title %>
</div>
<div class="form-group">
<%= f.label :price %>
<%= f.number_field :price %>
</div>
<div class="form-group">
<%= f.label :book_id %>
<%= f.text_field :book_id %>
</div>
<div class="form-group">
<%= f.label :publisher %>
<%= f.text_field :publisher %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_field :description%>
</div>
<div class="form-group">
<%= f.label :number %>
<%= f.number_field :number %>
</div>
<div class="form-group">
<%= f.submit %>
</div>
<% end %>
</div>

bookstore_app/app/views/books/show.html.erb
<div class="container">
<h3>Book Details</h3>
<p>Book Title: <%= @book.title %> </p>
<p>Book price: <%= @book.price %> </p>
<p>Book publisher: <%= @book.publisher %> </p>
<p>Book number: <%= @book.number %> </p>
<p>Book description: <%= @book.description %> </p>
<p>Book id: <%= @book.book_id %> </p>
</div>

bookstore_app/app/views/genres/index.html.erb
<div class="container">
<h2> Genre </h2>
<table border="1" class="table">
<tr>
<th> Genre Name</th>
</tr>
<% @genres.each do |genre| %>
<tr>
<td> <%= genre.name %> </td>
</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/genres/new.html.erb
<div class="container">
<h2>Add New Genre</h2>
<%= form_for :genre, url: genres_path do |f| %>
<div class="form-group">
<%= f.label :name %><br />
<%= f.text_field :name, class:'form-control' %><br />
</div>

<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", genres_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/genres/show.html.erb
<div class="container">
<h3>Genre Details</h3>
<p>Genre Name: <%= @genre.name %> </p>
</div>

bookstore_app/app/views/novels/edit.html.erb
<div class = "container">
<%= form_for @novel do |f| %>
  <div class="form-group">
<%= f.label :name %><br />
<%= f.text_field :name, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :description %><br />
<%= f.text_field :description, class:'form-control' %><br />
</div>
<%= f.label :isbn %><br />
<%= f.text_field :isbn, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :price %><br />
<%= f.number_field :price, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :pages %><br />
<%= f.number_field  :pages, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :publication %><br />
<%= f.date_field  :publication, class:'form-control' %><br />
</div>
<%= f.label :format %><br />
<%= f.text_field :format, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :genre %><br />
<%= f.select :genre_id, Genre.all.collect {|x| [x.name,
x.id]}, {:include_blank => 'Select Genre'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
<%= f.label :genre %><br />
<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,
x.id]}, {:include_blank => 'Select publisher'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
<%= f.label :author %><br />
<%= f.select :author_id, Author.all.collect {|x| [x.fname , x.id]}, {:include_blank => 'Select Author'},class:'form-control' %> <br /><br />
</div>
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", novels_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/novels/index.html.erb
<div class="container">
<h2> NOVEL </h2>
<table border="1" class="table">
<tr>
<th> Novel Name</th>
<th> isbn</th>
<th> price</th>
<th> Publication </th>
<th> format</th>
<th> pages</th>
<th> description</th>
<th> author id </th>
<th> genre id </th>
<th> publisher id </th>
<th> details </th>
<th> edit </th>
<th> delete </th>
</tr>
<% @novels.each do |novel| %>
<tr>
<td> <%= novel.name %> </td>
<td> <%= novel.isbn %> </td>
<td> <%= novel.price %> </td>
<td> <%= novel.publication %> </td>
<td> <%= novel.format %> </td>
<td> <%= novel.pages %> </td>
<td> <%= novel.description %> </td>
<td> <%= novel.author_id %> </td>
<td> <%= novel.genre_id %> </td>
<td> <%= novel.publisher_id %> </td>

<td> <%= link_to 'Novel', novels_path(novel) %> </td>



<td> <%= link_to 'Edit', edit_novel_path(novel) %> </td>
<td> <%= link_to 'Delete', novel_path(novel),
method: :Delete,
data: {confirm: "Are you sure you want to delete details"}
%> </td>

</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/novels/new.html.erb
<div class="container">
<h2>Add New Novel</h2>
<%= form_for :novel, url: novels_path do |f| %>
<div class="form-group">
<%= f.label :name %><br />
<%= f.text_field :name, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :description %><br />
<%= f.text_field :description, class:'form-control' %><br />
</div>
<%= f.label :isbn %><br />
<%= f.text_field :isbn, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :price %><br />
<%= f.number_field : :price, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :pages %><br />
<%= f.number_field : :pages, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :publication %><br />
<%= f.date_field : :publication, class:'form-control' %><br />
</div>
<%= f.label :format %><br />
<%= f.text_field :format, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :genre %><br />
<%= f.select :genre_id, Genre.all.collect {|x| [x.name,
x.id]}, {:include_blank => 'Select Genre'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
<%= f.label :genre %><br />
<%= f.select :publisher_id, Publisher.all.collect {|x| [x.name,
x.id]}, {:include_blank => 'Select Genre'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
<%= f.label :author %><br />
<%= f.select :author_id, Author.all.collect {|x| [x.fname
+ ' '+ x.lname, x.id]}, {:include_blank => 'Select
Author'},class:'form-control' %><br /><br />
</div>
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", novels_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/novels/show.html.erb
<div class="container">
<h3>novel Details</h3>


<h1>  name :<%= @novel.name %> </h1>
<h1> isbn : <%= @novel.isbn %> </h1>
<h1> price: <%= @novel.price %> </h1>
<h1> publication: <%= @novel.publication %> </h1>
<h1>  format: <%= @novel.pages %> </h1>
<h1> description: <%= @novel.description %> </h1>
<h1> author_id:  <%= @novel.author_id %> </h1>
<h1> <%= link_to 'author', authors_path(@novel.author_id) %> </h1>

<h1> <%= link_to 'Genre', genres_path(@novel.genre_id) %> </h1>


<h1> publisher id <%= @novel.publisher_id %> </h1>

<h1> <%= link_to 'Novel', novels_path(@novel) %> </h1>



<h1> <%= link_to 'Edit', edit_novel_path(@novel) %> </h1>
<h1> <%= link_to 'Delete', '#' %> </h1>


</div>

bookstore_app/app/views/publisher/index.html.erb
<div class="container">
<h2> publisher </h2>
<table border="1" class="table">
<tr>
<th> Publisher Name</th>
<th> Country </th>
</tr>
<% @publishers.each do |publisher| %>
<tr>
<td> <%= publisher.name %> </td>
<td> <%= publisher.country %> </td>

</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/publisher/new.html.erb
<div class="container">
<h2>Add New Publisher</h2>
<%= form_for :publisher, url: publisher_path do |f| %>
<div class="form-group">
<%= f.label :name %><br />
<%= f.text_field :name, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :country %><br />
<%= f.text_field :country, class:'form-control' %><br />
</div>

<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", publisher_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/publisher/show.html.erb
<div class="container">
<h3>Publisher Details</h3>
<p>Publisher Name: <%= @publisher.name %> </p>
<p>Publisher Country: <%= @publisher.country %> </p>

</div>

bookstore_app/app/views/publishers/index.html.erb
<div class="container">
<h2> publisher </h2>
<table border="1" class="table">
<tr>
<th> Publisher Name</th>
<th> Country </th>
</tr>
<% @publishers.each do |publisher| %>
<tr>
<td> <%= publisher.name %> </td>
<td> <%= publisher.country %> </td>

</tr>

<% end %>
</table>
</div>

bookstore_app/app/views/publishers/new.html.erb
<div class="container">
<h2>Add New Publisher</h2>
<%= form_for :publisher, url: publishers_path do |f| %>
<div class="form-group">
<%= f.label :name %><br />
<%= f.text_field :name, class:'form-control' %><br />
</div>
<div class="form-group">
<%= f.label :country %><br />
<%= f.text_field :country, class:'form-control' %><br />
</div>

<%= f.submit "Submit", class:'btn btn-primary' %>
<%=link_to "Cancel", publishers_path, class:'btn btn-default' %>
<% end %>
</div>

bookstore_app/app/views/publishers/show.html.erb
<div class="container">
<h3>Publisher Details</h3>
<p>Publisher Name: <%= @publisher.name %> </p>
<p>Publisher Country: <%= @publisher.country %> </p>

</div>

bookstore_app/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

bookstore_app/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col">
      <h3>Contact Form</h3>


<form>
  <div class="form-group">
   <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Select country</label>
    <select class="form-control" id="country" name="country">
     <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>
  </div>
  
  <div class="form-group">
    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
  </div>
      <input type="submit" value="Submit">

</form>






</div>
</div>
</div>

bookstore_app/app/views/static_pages/home.html.erb
<div class="container">
<h1 class="jumbotron-heading"> Album</h1>
<div class="container">
<div class="row">
<div class="container">
</div>
</div>


<h1> gfdsa jhgfrsahgrsiuhgfrws </h1>
</div>